[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "./"
  filePath = "./sitemap.xml"

[[redirects]]
  from = "https://altawasol.netlify.app/*"
  to = "https://altawasolclean.com/:splat"
  status = 301
  force = true
